### ISSUE TITLE
ESP-WROOM-32 No response over http

### ISSUE THREAD

**Issue by pyr0ball** [SpoturDeal/ESP32Stepper#1]
I've got this project running on one of the devkit ESP-WROOM-32 boards, and it works fine through the API calls (using http://<IP>/stepper/percent?## works fine), but no UI like what's shown in the description of this project comes up and no response is given: 

```
 $ ping espressif.lan
PING espressif.lan (192.168.86.30) 56(84) bytes of data.
64 bytes from espressif.lan (192.168.86.30): icmp_seq=1 ttl=255 time=90.2 ms
 $ curl http://espressif.lan/stepper/percent?10
curl: (52) Empty reply from server
 $
```
I'd be happy to help debug if I get some direction

**Comment by SpoturDeal** [comment]
What is the output in your serial monitor?

**Comment by pyr0ball** [comment]
I realized I hadn't been running with debug enabled, so I'll try that when
I get back into the office tomorrow and check for output

On Jul 12, 2018 11:25 PM, "Carl" <notifications@github.com> wrote:

What is the output in your serial monitor?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SpoturDeal/ESP32Stepper/issues/1#issuecomment-404738690>,
or mute the thread

**Comment by pyr0ball** [comment]
With debug enabled, serial is outputting just this:

```
GET / HTTP/1.1
```

if I send a command:

```
GET /stepper/percent?1 HTTP/1.1
Request steps: 1 HTTP/1.1
Down to position 368
Stop
```

Still getting just an empty response from the curl command, no web interface using any browser

**Comment by SpoturDeal** [comment]
It should start with WiFi connected and WiFi address.
can you check if you have the latest versie of  #include <WiFi.h>

also try to add a extra
```
WiFiClient client = server.available();        // listen for incoming clients
Serial.println(client);  <<<<add this
if (client) { 
``` 

Check in the serial monitor what the reply is.

**Comment by pyr0ball** [comment]
When I connect the serial client, it does show the ssid and IP address as
connected, so there's that. I'll add the extra print line in as well. Any
other spots that would be handy to get feedback from?

**Comment by SpoturDeal** [comment]
You should just enter http://192.168.86.30 in your browser. (if there is api in the url you have no webinterface, /api/ is used for domoticz commands)

I am busy to rewrite some code to have it based also on MQTT

**Comment by pyr0ball** [comment]
Those responses I showed were from just the IP at first:

```

curl http://espressif.lan

curl: (52) Empty reply from server

```

**Comment by SpoturDeal** [comment]
can you try:

`curl http://192.168.86.30/stepper/percent?10`

**Comment by pyr0ball** [comment]
```
pi@octopi:~ $ curl http://192.168.86.30/stepper/percent?10
curl: (52) Empty reply from server
```

Just FYI I haven't added the new line yet, as I'm not in person with the
device and need to hold the boot button to flash it

**Comment by SpoturDeal** [comment]
I will order an esp-wroom-32 and see if I can duplicate the issue.

**Comment by pyr0ball** [comment]
[This is the version I'm using](https://www.amazon.com/HiLetgo-ESP-WROOM-32-Development-Microcontroller-Integrated/dp/B0718T232Z/ref=sr_1_3?ie=UTF8&qid=1531589409&sr=8-3&keywords=esp-wroom-32&dpID=51iO%252BJNDM6L&preST=_SY300_QL70_&dpSrc=srch)

**Comment by SpoturDeal** [comment]
Hello pyrOball,

I was able to duplicate your issue.

In the esp-wroom-32 (the one that you are using) you can remove  `client.flush();`  (line 88 and line 134)
after I did this i got the interface in the browser.

**Comment by pyr0ball** [comment]
Sweet! I'll give that a try in the morning.

**Comment by pyr0ball** [comment]
Confirmed! Removing those lines fixed the web GUI issue
