### ISSUE TITLE
'endedAT' not defined

### ISSUE THREAD

**Issue by pyr0ball** [SpoturDeal/ESP32Stepper#5]
After pulling the latest set of commits I found a couple things that are preventing compilation.

First is the int definitions for the microsteps are disparate from the pinmode and the rest of the sketch (My bad, cus that came from my PR):

```
int MicroStep1Pin = 34; // Stepper MS1
int Microstep2Pin = 35; // Stepper MS2
int Microstep3Pin = 32; // Stepper MS3
```
```
  pinMode(MicroStep1Pin, OUTPUT);	//set Microstep 1 config
  pinMode(MicroStep2Pin, OUTPUT);	//set Microstep 2 config
  pinMode(MicroStep3Pin, OUTPUT);	//set Microstep 3 config
```
Notice the capitalization is different.

Second is at line 331:
```
void stopRoll(){
    // write current position to EEprom
    writeData(EEcurrStep,endedAT);
    if (debugPrint ==true){
       Serial.println("Stop");
    }
    digitalWrite(EnablePin, LOW);
    digitalWrite(DirPin, HIGH);
    delay(1000);
    digitalWrite(EnablePin, HIGH);
}
```

something is funky with this syntax cus it can't be compiled due to endedAT not being defined. That's one I'm not sure how to fix while still preserving the EEPROM additions

**Comment by SpoturDeal** [comment]
I have fixed the problem endedAT (don't know where that came from) is currPos. This stores the last position into EEprom. Also the typos in line 28 and 29 are fixed. 

It compiles fine with PlatformIO

![compiled](https://user-images.githubusercontent.com/26565921/44194195-8c100980-a135-11e8-9f2d-e7fe9965691a.png)

**Comment by SpoturDeal** [comment]
All solved
