### ISSUE TITLE
brower window no message，jast "Bad response. The server or forwarder response doesn't look like HTTP."

### ISSUE THREAD

**Issue by cqliliping** [SpoturDeal/ESP32Stepper#6]
hello SpoturDeal
  I meet a question,in serial mornitor,it's normal presenting with "
WiFi connected
IP address: 
192.168.2.88
Place this IP address into a browser window"
  but in my brower window,there is nothing
![image](https://user-images.githubusercontent.com/35253269/50585970-72881800-0eb2-11e9-8f6f-c26dad9c717d.png)

maybe i need understand " String userResponsePage(String req) ",isn't it?

**Comment by SpoturDeal** [comment]
The function String userResponsePage(String req) is a function that returns a text in an HTML format.

Can you enter 

192.168.2.88/api

or

http://192.168.2.88

To see if this gives a reaction.

**Comment by cqliliping** [comment]
> The function String userResponsePage(String req) is a function that returns a text in an HTML format.
> 
> Can you enter
> 
> 192.168.2.88/api
> 
> or
> 
> http://192.168.2.88
> 
> To see if this gives a reaction.

hello SpoturDeal
  i tried  192.168.2.88/api or http://192.168.2.88,got the same bad responed.but when i turn off SSR(ShadowsocksR) , HTML look likes work normally.
![image](https://user-images.githubusercontent.com/35253269/50870632-cd11fe80-13f3-11e9-9eaa-c2c976a12f08.png)

**Comment by SpoturDeal** [comment]
That looks like it should be.

Using a proxy on a .local network can always give problems, because the proxy is not .local

**Comment by stay-foolish8** [comment]
your VPN pattern could be in global pattern.
you can try in PAC pattern.
