### ISSUE TITLE
Voltage mismatch issue

### ISSUE THREAD

**Issue by h0oni** [SpoturDeal/ESP32Stepper#7]
I am not 100% sure but ain't the GPIO pins of esp32 only outputs 3.3V? So won't that create a problem with a4988?

**Comment by SpoturDeal** [comment]
You don't get the 5v from the ESP but from the 5V line of your powersupply

**Comment by h0oni** [comment]
Oh. Hello. I didn't mean that. The dir step and enable pins of A4988 to require 5V signals if I am not wrong. So if the esp outputs 3.3V. Won't that be a problem?

**Comment by SpoturDeal** [comment]
That is not a problem I am using this config quite a long time without any problems.
